# Generated by Django 3.2.7 on 2021-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_privatechatroom_connected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
